### ISSUE TITLE
Need the test data used in the model

### ISSUE THREAD

**Issue by PuziJiang** [gc-js/Antimicrobial-peptide-generation#2]
Dear Sir, 
We are building an AMP model and are searching for an independent dataset for model comparison. I found that you compared your model to other public models on the independent test data (that contains 162 AMPs that were newly discovered in 2022 from the APD3 database and a total of 111 373 non-AMPs from the Sidorczuk et al study).  However, I did not find the test data in the supplementary file and github. The APD3 database mentioned that they updated ~ 200 AMPs in 2022, inconsistent with the article.  Could you please provide the test data? Looking forward to your reply!
<img width="778" alt="image" src="https://github.com/user-attachments/assets/a13b103e-738a-4dbc-8c32-98590efed8b5">

**Comment by gc-js** [comment]
You can find  it from here. ![image](https://github.com/user-attachments/assets/1b01b7b4-7c6d-4c0f-bad9-77343fb32a70)
